@echo off
echo Parando processos Node.js...
taskkill /F /IM node.exe 2>nul

echo Limpando cache...
if exist .next rmdir /s /q .next

echo Gerando Prisma Client...
npx prisma generate

echo Iniciando servidor...
npm run dev
